/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VendingMachine } from "./VendingMachine";
export * as factories from "./factories";
export { VendingMachine__factory } from "./factories/VendingMachine__factory";
