/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface VendingMachineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addProduct"
      | "contractBalance"
      | "getAllProducts"
      | "getOwnedQuantity"
      | "getProduct"
      | "ownedItems"
      | "owner"
      | "productCount"
      | "products"
      | "purchase"
      | "restock"
      | "setPrice"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FundsWithdrawn"
      | "ItemPurchased"
      | "ProductAdded"
      | "ProductRestocked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addProduct",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllProducts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnedQuantity",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProduct",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ownedItems",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "productCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "products",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchase",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "restock",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addProduct", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllProducts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnedQuantity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProduct", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownedItems", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "productCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "products", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "purchase", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "restock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ItemPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    productId: BigNumberish,
    productName: string,
    quantity: BigNumberish,
    totalPaid: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    productId: bigint,
    productName: string,
    quantity: bigint,
    totalPaid: bigint
  ];
  export interface OutputObject {
    buyer: string;
    productId: bigint;
    productName: string;
    quantity: bigint;
    totalPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductAddedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    name: string,
    price: BigNumberish,
    initialStock: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    name: string,
    price: bigint,
    initialStock: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    name: string;
    price: bigint;
    initialStock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductRestockedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    productName: string,
    newStock: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    productName: string,
    newStock: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    productName: string;
    newStock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VendingMachine extends BaseContract {
  connect(runner?: ContractRunner | null): VendingMachine;
  waitForDeployment(): Promise<this>;

  interface: VendingMachineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addProduct: TypedContractMethod<
    [name: string, price: BigNumberish, initialStock: BigNumberish],
    [void],
    "nonpayable"
  >;

  contractBalance: TypedContractMethod<[], [bigint], "view">;

  getAllProducts: TypedContractMethod<
    [],
    [
      [bigint[], string[], bigint[], bigint[]] & {
        ids: bigint[];
        names: string[];
        prices: bigint[];
        stocks: bigint[];
      }
    ],
    "view"
  >;

  getOwnedQuantity: TypedContractMethod<
    [user: AddressLike, productId: BigNumberish],
    [bigint],
    "view"
  >;

  getProduct: TypedContractMethod<
    [productId: BigNumberish],
    [[string, bigint, bigint] & { name: string; price: bigint; stock: bigint }],
    "view"
  >;

  ownedItems: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  productCount: TypedContractMethod<[], [bigint], "view">;

  products: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        name: string;
        price: bigint;
        stock: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  purchase: TypedContractMethod<
    [productId: BigNumberish, quantity: BigNumberish],
    [void],
    "payable"
  >;

  restock: TypedContractMethod<
    [productId: BigNumberish, additionalStock: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPrice: TypedContractMethod<
    [productId: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addProduct"
  ): TypedContractMethod<
    [name: string, price: BigNumberish, initialStock: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "contractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllProducts"
  ): TypedContractMethod<
    [],
    [
      [bigint[], string[], bigint[], bigint[]] & {
        ids: bigint[];
        names: string[];
        prices: bigint[];
        stocks: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwnedQuantity"
  ): TypedContractMethod<
    [user: AddressLike, productId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProduct"
  ): TypedContractMethod<
    [productId: BigNumberish],
    [[string, bigint, bigint] & { name: string; price: bigint; stock: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "ownedItems"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "productCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "products"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        name: string;
        price: bigint;
        stock: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "purchase"
  ): TypedContractMethod<
    [productId: BigNumberish, quantity: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "restock"
  ): TypedContractMethod<
    [productId: BigNumberish, additionalStock: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPrice"
  ): TypedContractMethod<
    [productId: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ItemPurchased"
  ): TypedContractEvent<
    ItemPurchasedEvent.InputTuple,
    ItemPurchasedEvent.OutputTuple,
    ItemPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "ProductAdded"
  ): TypedContractEvent<
    ProductAddedEvent.InputTuple,
    ProductAddedEvent.OutputTuple,
    ProductAddedEvent.OutputObject
  >;
  getEvent(
    key: "ProductRestocked"
  ): TypedContractEvent<
    ProductRestockedEvent.InputTuple,
    ProductRestockedEvent.OutputTuple,
    ProductRestockedEvent.OutputObject
  >;

  filters: {
    "FundsWithdrawn(address,uint256)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "ItemPurchased(address,uint8,string,uint256,uint256)": TypedContractEvent<
      ItemPurchasedEvent.InputTuple,
      ItemPurchasedEvent.OutputTuple,
      ItemPurchasedEvent.OutputObject
    >;
    ItemPurchased: TypedContractEvent<
      ItemPurchasedEvent.InputTuple,
      ItemPurchasedEvent.OutputTuple,
      ItemPurchasedEvent.OutputObject
    >;

    "ProductAdded(uint8,string,uint256,uint256)": TypedContractEvent<
      ProductAddedEvent.InputTuple,
      ProductAddedEvent.OutputTuple,
      ProductAddedEvent.OutputObject
    >;
    ProductAdded: TypedContractEvent<
      ProductAddedEvent.InputTuple,
      ProductAddedEvent.OutputTuple,
      ProductAddedEvent.OutputObject
    >;

    "ProductRestocked(uint8,string,uint256)": TypedContractEvent<
      ProductRestockedEvent.InputTuple,
      ProductRestockedEvent.OutputTuple,
      ProductRestockedEvent.OutputObject
    >;
    ProductRestocked: TypedContractEvent<
      ProductRestockedEvent.InputTuple,
      ProductRestockedEvent.OutputTuple,
      ProductRestockedEvent.OutputObject
    >;
  };
}
